### ISSUE TITLE
Issue with gaps in CSS-Grid Layout

### ISSUE THREAD

**Issue by jmweiss87** [jmweiss87/thinkfulTube#1]
I'm currently having an issue with gaps in my CSS-Grid. The page represents the search results using a YouTube API. I have used the standard div wrapper for my grid elements, and within those elements are my grid items. The results for the query show the image, the title, and the description. The issue is that the description (of the query result) is stretching the grid box in such a way that causes everything to be off center once the screen width is past a certain point (dragging your browser past 900px or so). I am including a screenshot with the issue highlighted via Chrome Dev Tools, as well as a link to the live version hosted by GitHub pages. Any help is appreciated, and yes I am new the Grid. Best, John
https://jmweiss87.github.io/thinkfulTube/
![issue-css-grid-gaps](https://user-images.githubusercontent.com/5333491/38831649-0ca7ce3c-418e-11e8-9bc0-f639b3aae7e5.png)

**Comment by rosaxxny** [comment]
Maybe this will help? https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Realizing_common_layouts_using_CSS_Grid_Layout

**Comment by benjaminmodayil** [comment]
I don't think your issue is with the grid gaps. I pulled down your repo and I think the only issue is that you don't have anything aligning the thumbnail to the center once each column gets wider as shown in your thumbnail. 

Two ways of fixing this, **but both require you adding a class** on the `<a>` element that holds your thumbnail image:

1. Add the following to that previously mentioned class:
- `display: flex;`
- `justify-contents: center;`

2. or just add:
- `text-align: center;`


![image](https://user-images.githubusercontent.com/12306850/38935261-eb806b9c-42eb-11e8-8b68-762ff6006418.png)

**Comment by jmweiss87** [comment]
Thanks for taking a look at my first go at the CSS-Grid! Your advice was very helpful and helped me solve the problem almost instantly. 
- @rosaxny Thanks for the direct link to that CSS-Grid Guide on MDN. While I had been on MDN looking at various parts of the grid (as well as other sites), I had not run into that part yet. Explains much of what you need to know at a fast pace.
- @benjaminmodayil  Thank you for going the distance and actually diving into the code. Props for that. What you said is correct, but it also brought another point up to me, that my current class of js-result-items was attached to all my query results, _except_ for the anchor tag around the thumbnail. I had instead attached the class to the actual img (errr), so that was an insta-fix, because you had mentioned the <a> tag, and I was thinking I had put it there. I indeed had, but had not attached the class to the right tag. 
Thanks again.
Cheers,
John
